### ISSUE TITLE
Incorrect playback state for livestream without DVR when the playback interrupted by the system

### ISSUE THREAD

**Issue by pyby** [SRGSSR/srgletterbox-apple#185]
From the Letterbox specification, a livestream without DVR window can't be in the pause state. It can only have `play` and `idle` playback state.
The user must always in the live condition, as there is no seek bar or seek buttons.

### Issue type

Incorrect behavior

### Description of the problem

When the playback is interrupted by the system, like a alarm, or an other application takes the audio session, the controller goes in the pause state, even if it's a `SRGMediaPlayerStreamTypeLive` content.

### Environment information

* Library version: 1.15
* iOS version: Any
* Device: Any

### Reproducibility

Always reproducible

### Steps to reproduce

More easy to see on an iPad with a video livestream, but this not only on this device and this kind of media.

1. Open Letterbox Demo in split view with an other music / video app in the other side. (Like a Play SRG app or an other Letterbox demo app).
2. Play a "live only" video on Letterbox Demo. The player has only "Play" and "Stop" buttons (no "Pause" button. ie: [MMF Topics / bipbop RTSInfo Tagesschau24 / Tagesschau24 (ARD, live only)](http://play-mmf.herokuapp.com/mmf/media/urn:rts:video:_tagesschau24_ard_liveonly)
3. On the other app, start an audio or a video.

Letterbox Demo player stops the playback but don't stops de AVPlayer. The frame is in pause and when tapping on the Play button, it resumes it. The stream isn't in live condition anymore.

**Comment by pyby** [comment]
See `feature/playback-interruption`.

**Comment by defagos** [comment]
Merged into `develop`.
