### ISSUE TITLE
Incorrect control center slider behavior

### ISSUE THREAD

**Issue by defagos** [SRGSSR/srgletterbox-apple#200]
After having played a DVR stream for a few minutes, the slider in the control center does not seek at the location it is released at. In particular, attempting to slide to live conditions is not possible anymore, as the slider ends a few minutes before the end of the stream.

### Issue type

Incorrect behavior

### Environment information

* Library version: 3.0.0
* iOS version: Any
* Device: Physical

### Reproducibility

Always reproducible

### Steps to reproduce

1. Open Letterbox demo and play Couleur 3
1. Wait a few minutes
1. From the control center, seek to the past, then attempt to seek back to the live.

**Comment by pyby** [comment]
Fix proposition was in 'feature/energy-efficiency`. Merged.
