### ISSUE TITLE
VoiceOver issue when SRGLetterboxController is in full screen

### ISSUE THREAD

**Issue by va1da** [SRGSSR/srgletterbox-apple#205]
When VoiceOver is active in my app and the `SRGLetterboxController` is in the fullscreen mode it looks like someone is repeatedly posting `UIAccessibility.post(notification: .screenChanged)` notification (in about 3 second intervals). This causes that each time the first element on the screen is focused and it interrupts voice over every time I'm trying to select any other control on the screen.

I tested this issue with my offline view implementation which is using `SRGMediaPlayerController` and the problem is not present there.

Is it possible that `SRGLetterboxController` is posting this kind of notification internally for some reason?

Thanks.

**Comment by defagos** [comment]
Hi! 

As far as I remember, we only post announcements when displaying a notification banner on Letterbox view. `SRGLetterboxController` itself has never implemented any VoiceOver feature, as it is inherently non-interactive.

Which version of Letterbox are you using?

**Comment by va1da** [comment]
Hi, here is my `cartfile.resolved`
```
github "Mantle/Mantle" "2.1.0"
github "SRGSSR/ComScore-iOS-watchOS-tvOS" "5.8.4"
github "SRGSSR/FXReachability" "1.3.2_srg3"
github "SRGSSR/MAKVONotificationCenter" "1.0_srg3"
github "SRGSSR/Masonry" "v1.1.0_srg1"
github "SRGSSR/UICKeyChainStore" "v2.1.2_srg1"
github "SRGSSR/YYWebImage" "1.0.5_srg1"
github "SRGSSR/libextobjc" "0.6_srg1"
github "SRGSSR/srganalytics-ios" "3.7.4"
github "SRGSSR/srgappearance-ios" "1.1.10"
github "SRGSSR/srgcontentprotection-ios" "1.2.3"
github "SRGSSR/srgdataprovider-ios" "6.8"
github "SRGSSR/srgdiagnostics-ios" "1.0.1"
github "SRGSSR/srgidentity-ios" "1.0.4"
github "SRGSSR/srgletterbox-ios" "1.14.4"
github "SRGSSR/srglogger-ios" "1.1"
github "SRGSSR/srgmediaplayer-ios" "2.8"
github "SRGSSR/srgnetwork-ios" "1.0.3"
github "SRGSSR/tagcommander-ios" "4.3.3_4.3.1"
```

Maybe you are not posting accessibility notification manually but it could be posted as a result of some other action. Is there some kind of timer when letterbox is running which is doing something periodically?

**Comment by defagos** [comment]
Of course Letterbox internally uses a few timers. I recently had a look at all existing timers to reduce the need for them (an improvement which will be delivered in 2.0.1). I am certain there is no 3-second timer in Letterbox 1.14. Moreover, the calls we make to `UIAccessibilityPostNotification` are not related to any timers at all.

Could you make a symbolic breakpoint on `UIAccessibilityPostNotification` to find out who in your app is posting notifications?

**Comment by va1da** [comment]
Updated to the latest Letterbox and issue is not present anymore.

**Comment by defagos** [comment]
Great, thanks!
