### ISSUE TITLE
iOS and tvOS 14 official support

### ISSUE THREAD

**Issue by defagos** [SRGSSR/srgletterbox-apple#230]
Official iOS and tvOS support still needs to be tested and remaining issues have to be fixed:

- [x] Cell progress bars are taller than expected.

**Comment by pyby** [comment]
Same here. We'll have a look.
Thank you @cellos-bot for the feedback.

**Comment by pyby** [comment]
@cellos-bot , the Carthage issue with Xcode 12 is a known issue on their repository. https://github.com/Carthage/Carthage/issues/3019

From this thread, a workaround exists. Here is a proposition:
1. Add an executable file `carthage-build.sh` like:
```
#!/usr/bin/env bash

# carthage-build.sh
# Usage example: ./carthage-build.sh --platform iOS

set -euo pipefail

xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

# For Xcode 12 make sure EXCLUDED_ARCHS is set to arm architectures otherwise
# the build will fail on lipo due to duplicate architectures.
# Xcode 12 Beta 3:
echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_12A8169g = arm64 arm64e armv7 armv7s armv6 armv8' >> $xcconfig
# Xcode 12 beta 4
echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_12A8179i = arm64 arm64e armv7 armv7s armv6 armv8' >> $xcconfig
# Xcode 12 beta 5
echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_12A8189h = arm64 arm64e armv7 armv7s armv6 armv8' >> $xcconfig
# Xcode 12 beta 6
echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_12A8189n = arm64 arm64e armv7 armv7s armv6 armv8' >> $xcconfig
# Xcode 12 GM (12A7208)
echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_12A7208 = arm64 arm64e armv7 armv7s armv6 armv8' >> $xcconfig
# Xcode 12 GM (12A7209)
echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_12A7209 = arm64 arm64e armv7 armv7s armv6 armv8' >> $xcconfig

echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200 = $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_$(XCODE_PRODUCT_BUILD_VERSION))' >> $xcconfig
echo 'EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))' >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"
carthage build "$@"
```

2. Update or bootstrap without building, then use this script to build library dependencies:
```
carthage update --new-resolver --no-build # Or use bootstrap for a CI with a Cartfile.resolved
./carthage-build.sh --cache-builds --platform iOS,tvOS # Add --configuration Release-static if you choose static builds.
```

We hope it will be an old story soon, when we'll release with SPM support. See #217

**Comment by defagos** [comment]
We received the following question:

> Dear Letterbox Team, 

> I hope this email finds you well. I am contacting you regarding the current implementation of the Letterbox 5.0.2 in Meteo. (As we all know, Apple didn't give us much time :D)

> We are currently facing two problems in the development of Meteo 2.10:
> - The 5.0.2 Version is not supporting XCode 12 which would not allow us to release a version in iOS 14
> - In case you are converting to SPM, we might have a problem. We are not sure if SPM works with projects that still contain Objective-C code (which is Meteo's case)

> We were wondering if you are planning the next release in the short future. 

Yes, we are all facing the same issue and attempting our best to solve it. Sorry this impacts your team as well. To answer your concerns:

- The problem is actually to compile Letterbox 5.0.2 (soon 5.0.3, see below) with the iOS 14 SDK. This is related to an issue with Carthage and the new arm64 architecture support. Still if your project has a `Cartfile` to import Letterbox as dependency, you can tweak the `carthage` command with a simple shell script to work around this issue (see above). This is not optimal but as unobtrusive as possible. This is the best pragmatic option we can offer so that your migration is kept as simple as possible (though not without a bit of work on your side, of course). There are no API changes involved this way, so once Carthage can build the library dependencies you are good to go. Of course, we can help with this step you should the above instructions not be clear enough.
- SPM is only a dependency manager. Our Play SRG iOS project is actually written almost entirely in Objective-C as well. Letterbox itself is currently pure Objective-C as well. So there is no problem with the _S_ (for Swift) letter in SPM, in fact compiling and using Letterbox in any kind of project (Objective-C, Swift or mixed) will be very easy with SPM, as everything is natively managed by Xcode.

Note we will release a minor update 5.0.3 tomorrow, as comScore delivered an SDK update for iOS 14 which should be integrated in apps as early as possible. This SDK update was released after Letterbox 5.0.2 and we hadn't been informed before it would be required. We will communicate more information about it tomorrow, but the update procedure to 5.0.2 or 5.0.3 is exactly the same.

## Recommendations

In general we recommend the following approach for updating a project to 5.0.3:

- If your project can still be compiled with Xcode 11 and the iOS 13 SDK, use this tool version. Carthage will build dependencies fine and we have tested Letterbox fully for this setup.
- If you cannot (because you have to use Xcode 12 and iOS 14 SDK for widgets, for example), then use the above workaround and 5.0.3. We have tested this setup and we are confident it work exactly in the same way as the Xcode 11 and iOS 13 SDK, but tests have not been extensive. We have identified an issue and fixed it already in 5.0.2 and found no other problem, but this is a risk you must know of (though I would say it is very limited).

Once you could deliver your app update to the stores, you can breathe a bit. We are currently working on full iOS 14 SDK support in Letterbox 6.0.0. We plan to deliver this version in the upcoming weeks, with following features:

- This version will only support SPM, so you need to plan a bit of time for the migration. But if you could update to 5.0.3 easily, adopting SPM is basically throwing away Carthage, cleaning up references in your project, adding the dependency in Xode and using `@import` for Letterbox imports. We'll of course provide a detailed migration guide.
- Fully tested iOS 14 support, with one exception (background video playback, an iOS 14 system regression we need to work on with Apple directly).

Other 6.x versions will further improve compatibility with iOS 14, hopefully solving background video playback (but probably only on iOS 14.2 if we can have Apple deliver a fix for this version).

**Comment by pyby** [comment]
- To build **Letterbox 5.0.3 with Xcode 12, Carthage has now an official workaround**:
https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md
This workaround is more flexible with new Xcode version (like 12.0.1 or 12.1 GM version)

- Start using **Letterbox 6.0.0 with Xcode 12 and SPM support**. Here is our migration guide:
https://github.com/SRGSSR/srgletterbox-apple/wiki/Migration-guides
Letterbox 6.0.0 version is not yet released. But you can **use `develop` branch dependency** to start the migration.

**Comment by pyby** [comment]
🎉 [Letterbox 6.0.0](https://github.com/SRGSSR/srgletterbox-apple/releases/tag/6.0.0) is released.

The proposed [migration guide](https://github.com/SRGSSR/srgletterbox-apple/wiki/Migration-guides) is also available.
