### ISSUE TITLE
Better diagnostic error message

### ISSUE THREAD

**Issue by pyby** [SRGSSR/srgletterbox-apple#233]
### Issue type

Feature request

### Description of the problem

As a technical investigator, using the `SRGDiagnostic` reports, implementing in Letterbox, "Content can't be played" error message is not helpful.
A technical error message would be better.

### Environment information

* Library version: 5.X (and all previous)
* iOS version: Any
* Device: Any

**Comment by pyby** [comment]
Propositions:
1. Last Underlying localized description
2. Recursive error localized descriptions
3. Recursive error description like "Domain (code): localized description"


Test 1: "urn": "urn:rts:video:mediacomposition404",
1. "ilResult.errorMessage": "Not found"
2. "ilResult.errorMessage": "Not found"
3. "ilResult.errorMessage": "ch.srgssr.network (0): Not found"

Test 2: "urn": "urn:rts:video:playlist404",
1. "playerResult.errorMessage": "The operation couldn’t be completed. (CoreMediaErrorDomain error -12938 - The operation couldn’t be completed. (CoreMediaErrorDomain error -12938 - HTTP 404: File Not Found))",
2. "playerResult.errorMessage": "The media cannot be played; The requested URL was not found on this server.; The operation couldn’t be completed. (CoreMediaErrorDomain error -12938 - The operation couldn’t be completed. (CoreMediaErrorDomain error -12938 - HTTP 404: File Not Found))",
3. "playerResult.errorMessage": "ch.srgssr.mediaplayer (0): The media cannot be played; NSURLErrorDomain (-1100): The requested URL was not found on this server.; CoreMediaErrorDomain (-12938): The operation couldn’t be completed. (CoreMediaErrorDomain error -12938 - The operation couldn’t be completed. (CoreMediaErrorDomain error -12938 - HTTP 404: File Not Found))",

Test 3: "urn": "urn:rts:video:playlistInvalidHost",
1. "playerResult.errorMessage": "The operation couldn’t be completed. (OSStatus error 310.)",
2. "playerResult.errorMessage": "The media cannot be played; The operation could not be completed; The operation couldn’t be completed. (OSStatus error 310.)",
3. "playerResult.errorMessage": "ch.srgssr.mediaplayer (0): The media cannot be played; AVFoundationErrorDomain (-11800): The operation could not be completed; NSOSStatusErrorDomain (310): The operation couldn’t be completed. (OSStatus error 310.)",

**Comment by pyby** [comment]
Let decide which one is better for diagnostic:
- `feature/diagnostic-error-message-1`
- `feature/diagnostic-error-message-2`
- `feature/diagnostic-error-message-3`

**Comment by defagos** [comment]
I prefer option 1. It namely delivers the lowermost error message (thus the real error that triggered the error chain), which is really the most precise information we are interested in. The upper error levels are not that interesting and having a single value is probably better for reporting / consolidation purposes.

**Comment by pyby** [comment]
Thank you for your review. Option 1 is fine.

**Comment by pyby** [comment]
Option 1 is included in 6.1.0 release.
