### ISSUE TITLE
Upload to AppStore fails in app with widget

### ISSUE THREAD

**Issue by va1da** [SRGSSR/srgletterbox-apple#240]
Hi,
I was able to integrate Letterbox in my app succesfully tested it.

But when I try to upload the app into TestFligth I got this errors:
![Screenshot 2020-12-31 at 20 13 48](https://user-images.githubusercontent.com/961352/103442185-3da32d00-4c54-11eb-9238-ad244a99bde6.png)

My app contains also widget and for some reason it includes TC* and ComsScore frameworks inside and this causes duplicities.

So far my investigation narrowed to issue described here: 
https://github.com/renaudjenny/Swift-Package-Manager-Static-Dynamic-Xcode-Bug

Could you please confirm this issue?
Thanks.

**Comment by pyby** [comment]
We all have this SPM issue, because of binary dependencies.

We have a workaround described in our migration guide, by adding a post action script:
https://github.com/SRGSSR/srgletterbox-apple/wiki/Migration-guides#spm-53-plugin-embedded-binary-fix-xcode-120-and-above

**Comment by va1da** [comment]
Thanks, I missed that part of migration guide.
