### ISSUE TITLE
Send consistent environment for diagnostic report

### ISSUE THREAD

**Issue by pyby** [SRGSSR/srgletterbox-apple#241]
### Issue type

Feature request

### Description of the problem

Builds used for pre-production should send the `preprod` value for `environment` in the diagnostic report.

tvOS builds only have a TestFlight distribution. The current code returns `prod` for the diagnostic environment.

A recommandation should be to use `SRGAnalytics` tracker environment, if the tracker is instanced, use it to have the same diagnostic environment. See https://github.com/SRGSSR/srganalytics-apple/issues/37.

### Environment information

* Library version: 6.1.2
* iOS / tvOS version: Any
* Device: Any

### Reproducibility

Always reproducible

### Steps to reproduce

1. Play a media.
1. Wait at least 30 seconds, the diagnostic report is sent.
1. Verify the sent `environment` value.

**Comment by defagos** [comment]
I had a look at the branch, I just extracted the flag logic (as was already done for other flags).
