### ISSUE TITLE
Keyboard shortcut support

### ISSUE THREAD

**Issue by defagos** [SRGSSR/srgletterbox-apple#243]
We could add a way to control playback with the keyboard.

**Comment by defagos** [comment]
Sadly (or fortunately), due to how the keyboard shortcut registration API works, this cannot be implemented in a universal way by a Letterbox view. Since the view itself is not a first responder implementing it on the view does not work (shortcuts are never retrieved). And we cannot provide a Letterbox view method returning default shortcuts for direct use by a parent context, as the methods would then be defined on the view, not on the parent context, which means they wouldn't participate to the shortcut list either.

Fortunately this API is very simple to use and apps can implement shortcuts in a snap. This also avoids conflicts and is overall better IMHO. I thus updated the demo and documentation for more information about how such a feature can be implemented.

This is available on the `feature/keyboard-shortcuts` branch. I also exposed the standard Letterbox skip intervals so that applications can decide to use the same values when implementing shortcuts.

**Comment by pyby** [comment]
From a WWDC 2020, https://developer.apple.com/wwdc20/10109:

> Following the model-view-controller pattern, the ideal place to define this behavior is in your custom view controller subclass.

Thanks for the iteration.

**Comment by defagos** [comment]
I assigned this issue to milestone 6.2.0, as keyboard controls are available in the demo (and documentation has been updated accordingly).
