### ISSUE TITLE
AirPlay button incorrectly displayed for instances not registered with the service

### ISSUE THREAD

**Issue by defagos** [SRGSSR/srgletterbox-apple#264]
The AirPlay button should likely not be available if the controller attached to a Letterbox view is not the one registered with the Letterbox service.

This seems obvious, which explains why we should check a bit if this is intended behavior or some obvious bug we never saw. The button can be used to enable audio AirPlay (which is a use case in general), but in Letterbox this use case is probably covered well enough (and more consistently) through the control center.

### Issue type

Incorrect behavior

### Environment information

* Library version: 7.4.0
* iOS / tvOS version: iOS 15
* Device: Physical

### Reproducibility

Always reproducible

### Steps to reproduce

1. Open Letterbox demo.
1. Under the _Miscellaneous_ tab, open the standalone player SWI VOD example. 
1. The AirPlay button is visible.

**Comment by defagos** [comment]
Obvious fix available on `feature/airplay-button-fix`. Like every obvious fix, we probably should be extra careful the _fixed_ behavior was not _intended_ behavior.

**Comment by defagos** [comment]
Would revert #201. Needs to be discussed with @pyby first, but I am not sure I still agree with my old self :)

**Comment by pyby** [comment]
2022 discussed show be done again @defagos . Let's try your proposition. I agree with this approach, and Control center oriented.
