### ISSUE TITLE
Superfluous zoom gestures when zooming is not possible

### ISSUE THREAD

**Issue by defagos** [SRGSSR/srgletterbox-apple#272]
When zooming is not possible (e.g. full-screen playback of a 16:9 video on an iPhone SE) then the zoom gesture should not do anything. Currently it silently toggles content gravity, which means an extra pinch out gesture is required to exit full screen mode.

### Issue type

Incorrect behavior

### Environment information

* Library version: 8.2.0
* iOS: Any
* Device: Any

### Reproducibility

Always reproducible

### Steps to reproduce

> Provide step-by-step instructions about how to reliably reproduce the issue (or if not possible, with a good probability)

1. Comment out `-letterboxViewShouldDisplayFullScreenToggleButton:` in the advanced palyer demo.
1. Run the demo and play some media.
1. Rotate to landscape and pinch in to zoom. Nothing happens, but now you must pinch out twice to exit full screen (which is the case when setting sliders appear on top of the video in the tweaked advanced demo).

**Comment by defagos** [comment]
Available for review on `feature/pinch-improvements`.

I ensured that fill mode is not supported anymore if aspect ratios of the content / layer mismatch (up to some epsilon tolerance).

**Comment by pyby** [comment]
The check to fill gravity support wasn't call at good time when the controls with the timeline are animated automatically.

We iterated and decided to compare the presentation size to the Letterbox view size.

**Comment by defagos** [comment]
To improve overall consistency I propose that aspect fill is only available when the video view fills the entire player view frame. This avoids different behaviors between devices when segments are displayed, e.g. between an iPhone X and an iPhone SE.
