### ISSUE TITLE
Video freezes when skipping backwards from Control Center

### ISSUE THREAD

**Issue by NicolasBrunnerSRF** [SRGSSR/srgletterbox-apple#273]
### Issue type

Incorrect behavior

### Description of the problem

The video player shows the teaser image (instead of the running video / audio is fine) when skipping backwards from the Lockscreen Control Center and then reopening the app.

### Environment information

* Library version: 8.2.0
* iOS / tvOS version: iOS 15.3.1
* Device: iPhone 11 Pro (but also occurs on other devices (all?)) 

### Reproducibility

Always reproducible

### Steps to reproduce

1. Start a video (e.g. in "SRF Play" App or in the new "SRF News" App (release 09.08.2022))
2. Lock the screen (video continues playing)
3. skip backward in time (10s) over the control in the Lockscreen Control Center
4. Open App again --> Video Audio continues correctly, but Video Image is frozen (displaying teaser image) for 20s-25s

**Comment by defagos** [comment]
Thanks for the report. I guess this might be related to how we have to detach the video layer when the device is locked. Using the modern `audiovisualBackgroundPlaybackPolicy` API should be a possible solution to this issue.

**Comment by defagos** [comment]
No issue visible in Letterbox demo, Play SRF or SRF News on iOS 16.5. Likely a system issue which has been fixed. Closed
