### ISSUE TITLE
Update to Commanders Act version 5

### ISSUE THREAD

**Issue by defagos** [SRGSSR/srgletterbox-apple#283]
**As a member of the analytics team** I want results to be gathered with the [new Commanders Act platform](https://github.com/CommandersAct/iOSV5/tree/master/TCServerSide#migration-v4-to-v5) requiring version 5 of the SDKs to be running in mobile applications.

# Acceptance criteria

- The Commanders Act SDK has been updated.
- Integration documentation has been updated if needed.

# Tasks

- [x] Update SRG Analytics to version supporting Commanders Act version 5 (Related to https://github.com/SRGSSR/srganalytics-apple/issues/62).

**Comment by defagos** [comment]
Since we discussed to [remove the environment flag[(https://github.com/SRGSSR/srganalytics-apple/issues/62) in SRG Analytics we cannot determine the corresponding flag we were sending in diagnostics report. Shouldn't we also remove it?

**Comment by defagos** [comment]
Question for @StaehliJ and @amtins: Do you agree we could remove the `environment` field we send to Snitch in diagnostics reports (see previous message)?

@pyby and I agree this is a good idea since this value has probably been never used anyway.

**Comment by amtins** [comment]
@defagos I am not against deleting this field, even if we use it from time to time. However, we should not forget to update the specification [PerformanceReport.js#L59-L101](https://github.com/SRGSSR/srgletterbox-web/blob/master/src/diagnostics/PerformanceReport.js#L59-L101)
