### ISSUE TITLE
User consent

### ISSUE THREAD

**Issue by pyby** [SRGSSR/srgletterbox-apple#298]
**As a member of the analytics team** I want results to be gathered with the user consent new rules.

# Acceptance criteria

- The SRGAnalytics SDK has been updated.
- API to control user consent on SRG Snitch.
- Integration documentation has been updated if needed.

# Tasks

- [x] Update SRG Analytics to version supporting User Consent (Related to https://github.com/SRGSSR/srganalytics-apple/issues/66).

**Comment by r3econ** [comment]
Is there any update on this? When could this go live?

**Comment by defagos** [comment]
This has been delivered in version 9.1.1 of Letterbox.
