### ISSUE TITLE
For swift, map singleton to static var instead of function

### ISSUE THREAD

**Issue by vpdn** [SRGSSR/srgletterbox-apple#45]
### Issue overview

* [ ] Incorrect behavior
* [x] Feature request
* [ ] Crash
* [ ] Help / documentation
* [ ] Other: _classification_

### Description of the problem

It seems Apple is mapping singletons as static class variables now instead of a static function. For example `UIApplication.sharedApplication()` became 'UIApplication.shared" in swift 3. Maybe we should do the same (e.g. for SRGAnalyticsTracker).

### Discussion
Disclaimer: Usage seems still be pretty inconsistent even with Apple's own APIs. Lots of APIs still map to shared():

![image](https://cloud.githubusercontent.com/assets/387312/24394578/c9f67fc2-139c-11e7-9265-b0b1caf0aece.png)

whereas newer ones seem to be with a static var:

![image](https://cloud.githubusercontent.com/assets/387312/24394607/e6c9bbe6-139c-11e7-9c4c-4dd802d2b978.png)

**Comment by defagos** [comment]
Swift nowadays pretty well applies naming conventions to Objective-C code. No additional work is required.
