### ISSUE TITLE
Improve support for medias with non 16:9 ratios

### ISSUE THREAD

**Issue by defagos** [SRGSSR/srgletterbox-apple#81]
Letterbox was initially designed for medias with 16:9 ratios. We could improve support for other aspect ratios (1:1, 4:3, 21:9, etc.). This might require access to other image ratios for thumbnails and might therefore not be feasible in a near future (or at least not with a good result).

**Comment by defagos** [comment]
We have started working on this enhancement. The metadata can now be delivered by the IL and provided as information to clients when laying out a Letterbox view.

**Comment by defagos** [comment]
We have an implementation proposal. We will [implement it in Play SRG](https://github.com/SRGSSR/playsrg-ios/issues/136) to validate the API.

**Comment by pyby** [comment]
The `srg_replacementConstraintWithMultiplier:` helper on `NSLayoutConstraint` uses `[NSLayoutConstraint deactivateConstraints:@[ self ]];` which creates a recursive `layoutSubviews` call on iOS 9. Setting a strong reference does not change the behaviour.

Copying a layout contraint with a priority at 1000 works, but when the priority is under 1000 (required), a BAD_ACCESS execution is fired, after calling again.

For this reason, we decided to start `srg_replacementConstraintWithMultiplier:` helper support for iOS 10, and let decide each clients to support themself their constraints for iOS 9.
