### ISSUE TITLE
Add Cocoapods support

### ISSUE THREAD

**Issue by vpdn** [SRGSSR/srgletterbox-apple#99]
### Issue overview

We have a constellation that in my opinion, can only be cleanly resolved with cocoapods support for letterbox. So this is the request.

This is part of our dependency graph:

![image](https://user-images.githubusercontent.com/387312/33131179-096969b6-cf96-11e7-8e91-b81ea38bab04.png)

We depend on a subspec of YYImage to play back webp videos. Since carthage doesn't support "subspecs", the only way is to integrate it via cocoapods (or manually). From the [docs](https://github.com/ibireme/YYImage):

```
Notice: carthage framework doesn't include WebP component, if you want to support WebP format, use CocoaPods or install manually.
```

If we would manually integrate the library, things would break since SRGLetterbox itself also depends on the library and we would have duplicate symbols. Using Cocoapods also doesn't work for the same reason: SRGLetterbox would pull in the dependency via Carthage, the app would again pull in the same dependency via Cocoapods.

The only way I'm seeing forward would be precompile the SRGLetterbox framework and integrate it via Cocoapods as a binary dependency, or alternatively having you support Cocoapods. Or maybe you see another way that I'm missing?

Our current workaround is to *not* have a library for our fullscreen view controller and duplicate it in both app. Then pull in the carthage dependencies directly into the apps (news & sport).

![image](https://user-images.githubusercontent.com/387312/33131634-7f6eb534-cf97-11e7-9ed6-d64b8b67270b.png)

But even in this case, YYImage will still have duplicate symbols obviously and the behaviour isn't determined. Also we will have to make sure that the library will never diverge from the version letterbox is using. There's no way to say: "just use the version whatever letterbox is using" (in the cocoapods world that would be a dependency without version specifier).

**Comment by defagos** [comment]
Version 6.0.0 introduces SPM. Teams have agreed to use it for libraries (including SRF Sports and News teams). We can now forget that CocoaPods even existed.
